#!/usr/bin/env ruby

puts Dir.pwd.inspect

require "./config/git_hooks/metric_gem_handler.rb"

# Get the ruby gem version

handler = MetricGemHandler.new(:commit)
success = true
success = success && handler.exec("rails_best_practices .")

if success 
  puts "Success"
  exit(0)
else
  puts "Failed"
  exit(1)
end
