#!/usr/bin/env ruby

#!/usr/bin/env ruby

require "./config/git_hooks/metric_gem_handler.rb"

# Get the ruby gem version

handler = MetricGemHandler.new(:push)
success = true

metric_gems = {
  :rails_best_practices => "rails_best_practices .",
  :rubocop => "rubocop --rails --config ./config/rubocop_settings.yml ./lib ./spec ./app ./config",
  :metric_fu => "metric_fu --no-open",
}

metric_gems.each do |gem,cmd|
  success = success && handler.exec(gem.to_s,cmd)
end


if success 
  exit(0)
else
  MetricGemHandler.print_error
  exit(1)
end