#!/usr/bin/env ruby

require "./config/git_hooks/metric_gem_handler.rb"

# Get the ruby gem version

handler = MetricGemHandler.new(:commit)
success = true

metric_gems = {
  :rails_best_practices => "rails_best_practices .",
  :rubocop => "rubocop --rails --config ./config/rubocop_settings.yml ./lib ./spec ./app ./config",
  :metric_fu => "metric_fu --no-open",
}

metric_gems.each do |gem,cmd|
  success = success && handler.exec(gem.to_s,cmd) 
end

# No matter what on commit lets not keep the commit from happening
unless success 
  MetricGemHandler.print_error
end

exit(0)
