#!/usr/bin/env bash

# load rvm ruby
source "$HOME/.rvm/scripts/rvm"

rvm use ruby-2.0.0-p247@api.crunchinator.com

#bundle install
ruby -v

#lets get our current branch
branch=$(git branch | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')

# list of branches that we should not push to if there are errors
important_branches=( staging production development )

# Functions

in_array(){
    a=$2
    eval "for i in \${$a[@]}; do
        echo \$i
        test $1 = \$i && return 1
    done"
    return 0
}

# rails_best_practices .
if [ $(in_array $branch $important_branches) ]; then
  echo "Important Branch"
else
  echo "Stupid Branch"
fi
# if [[ $? != 0 ]]; then exit 1; fi
  

exit 0;