development:
  adapter: postgresql
  encoding: unicode
  database: crunchinator_development
  pool: 50
  username: postgres
  password: postgres
  host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['STAGING_POSTGRES_DATABASE'] %>
  pool: 50
  username: <%= ENV['STAGING_POSTGRES_USERNAME'] %>
  password: <%= ENV['STAGING_POSTGRES_PASSWORD'] %>
  host: <%= ENV['STAGING_POSTGRES_HOST'] %>
  port: <%= ENV['STAGING_POSTGRES_PORT'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: crunchinator_test
  pool: 50
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PRODUCTION_POSTGRES_DATABASE'] %>
  pool: 50
  username: <%= ENV['PRODUCTION_POSTGRES_USERNAME'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
  port: <%= ENV['PRODUCTION_POSTGRES_PORT'] %>